# Esto solo carga como un diccionario

video:

  video_path: /mnt/c/Users/UPS/Desktop/Proyecto Sewer-Seer/Desarrollo del Proyecto/Procesamiento de Imágenes/Videos_testbed/F0_C1_D1/_video_F0_C1_D_0.mp4


Diagnostic:
  # Debería ser el path donde está el servidor de mlflow
  mlflowuri: /mnt/c/........