# Esto solo carga como un diccionario

video:

  video_path: /mnt/c/Users/Jeankisshh/Desktop/SS_Image_Processing/Videos_testbed/F9_C1_D1/_video_F9_C1_D1_0.mp4


Diagnostic:
  mlflowuri:  http://localhost:5000

report:
  frames_dir: "/mnt/c/Users/Jeankisshh/Desktop/SS_Image_Processing/Video_Sessions/frames"
  db_url: "sqlite:////mnt/c/Users/Jeankisshh/Desktop/SS_Image_Processing/Video_Sessions/report.db"


  # /home/jeancarlo/vision_system/vision-system-ss/mlruns

  # mlflow server \
  #--backend-store-uri sqlite:///mlflow.db \
  #--default-artifact-root mlflow-artifacts:/ \
  #--serve-artifacts \
  #--host 0.0.0.0 \
  #--port 5000

# Ejecutar en terminal el servidor de mlflow así:
# mlflow server   --backend-store-uri sqlite:///mlflow.db   --default-artifact-root file:///home/jeancarlo/vision_system/vision-system-ss/mlruns   --serve-artifacts   --host 0.0.0.0   --port 5000